export const EVENT = {
  CLICK: 'click',
  DBLCLICK: 'dblclick',
  CONTEXTMENU: 'contextmenu',
  KEYDOWN: 'keydown',
  KEYUP: 'keyup',
  KEYPRESS: 'keypress',
  INPUT: 'input',
  CHANGE: 'change',
  FOCUS: 'focus',
  BLUR: 'blur',
  SUBMIT: 'submit',
  RESET: 'reset',
  MOUSEUP: 'mouseup',
  MOUSEDOWN: 'mousedown',
  MOUSEMOVE: 'mousemove',
  MOUSEENTER: 'mouseenter',
  MOUSELEAVE: 'mouseleave',
  WHEEL: 'wheel',
  SCROLL: 'scroll',
  RESIZE: 'resize',
  TOUCHSTART: 'touchstart',
  TOUCHMOVE: 'touchmove',
  TOUCHEND: 'touchend',
  POINTERDOWN: 'pointerdown',
  POINTERMOVE: 'pointermove',
  POINTERUP: 'pointerup',
} as const;

export type EventName = (typeof EVENT)[keyof typeof EVENT];
