docker:
  db: {}
domains: []
git:
  main_deployment_remote_name: github
  publication_strategy: main_push
global:
  name: js_helpers
  type: app
  version: 0.0.51
wex:
  migration: 1
  version: 6.0.112
